import fs from 'fs';
import { logger } from '../services/logger.js';
import { aiService } from '../services/aiService.js';
import { PromptBuilder } from '../services/promptBuilder.js';

/**
 * MockGenerator (v6.0)
 * Systematically transforms C++ headers into GMock headers following Workflow v05.
 */
export class MockGenerator {
  constructor() {
    this.promptBuilder = new PromptBuilder();
  }

  /**
   * Generates a transformed Mock header from a source file.
   * @param {string} headerPath Path to the source header (.h, .hpp)
   * @returns {Promise<Object>} The generated mock code and metadata.
   */
  async generateMock(headerPath) {
    if (!fs.existsSync(headerPath)) {
      throw new Error(`Header file not found: ${headerPath}`);
    }

    const headerContent = fs.readFileSync(headerPath, 'utf-8');
    const prompt = this.promptBuilder.buildMockTransformationPrompt(headerContent, headerPath);

    logger.log(`Transforming header: ${headerPath}`, 'MockGenerator');
    
    try {
      const response = await aiService.queryJSON(prompt);
      
      // v7.8.6: Broadened Validation (Accept code, generated_code, mock_code)
      const mockCode = response?.mock_code || response?.code || response?.generated_code || response?.mockCode;

      if (!mockCode) {
        const keys = response ? Object.keys(response).join(', ') : 'null';
        logger.error(`AI failed to generate mock code. Keys found: [${keys}]`, null, 'MockGenerator');
        throw new Error(`AI returned JSON but 'mock_code' field is missing. Keys: [${keys}]`);
      }

      logger.log(`Successfully generated mock for ${headerPath}`, 'MockGenerator');
      return {
        code: mockCode,
        thought_process: response.thought_process || response.explanation || response.strategy || "Generated by GTest Architect v7.8.6",
        singletons: response.singleton_mocks_created || response.singletons || []
      };
    } catch (err) {
      logger.error(`Transformation failed for ${headerPath}`, err, 'MockGenerator');
      throw err;
    }
  }
}
