import fs from 'fs';

/**
 * Ensures code generated by Gemini is safely appended to the workspace avoiding duplication.
 */
export class TestAccumulator {
  constructor() {}

  /**
   * Safely merges generated tests into the target file.
   */
  async accumulate(targetFile, newTestCases, includes = []) {
     if (!fs.existsSync(targetFile)) {
         return this.createNewFile(targetFile, newTestCases, includes);
     } else {
         return this.appendToFile(targetFile, newTestCases, includes);
     }
  }

  createNewFile(targetFile, newTestCases, includes) {
      let content = `// Auto-generated Test File\n`;
      includes.forEach(inc => content += `#include ${inc}\n`);
      content += `\n`;
      
      for (const t of newTestCases) {
          content += `// Scenario Intent: ${t.hint.reason_for_generation}\n`;
          content += `${t.code}\n\n`;
      }
      
      console.log(`[MERGE] Creating new file ${targetFile}`);
      // fs.writeFileSync(targetFile, content); // Dry run behavior mock
      return content;
  }

  appendToFile(targetFile, newTestCases, includes) {
      let content = fs.readFileSync(targetFile, 'utf-8');
      
      // Inject missing headers if necessary
      //! Advanced integration would inject headers elegantly below existing ones
      
      let newContentBlock = `\n// ---- AUTO-GENERATED APPENDAGES ----\n`;
      for (const t of newTestCases) {
          // Verify we aren't appending a test with the identical name
          const nameMatch = `TEST_F(${t.suite}, ${t.name})`;
          if (content.includes(nameMatch)) {
              console.warn(`[SKIP] Duplicate test name detected: ${nameMatch}`);
              continue;
          }
          newContentBlock += `// Hint: ${t.hint.reason_for_generation}\n`;
          newContentBlock += `${t.code}\n\n`;
      }
      
      console.log(`[MERGE] Appending to ${targetFile}`);
      return content + newContentBlock;
  }
}
